# Generated by Django 3.2.6 on 2021-08-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceShops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
